/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cigarette.glb --debug 
Author: RomanMaksy (https://sketchfab.com/RomanMaksy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cigarette-daily3d-eff40b1550e0466a9c3273a519139143
Title: Cigarette - daily3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cigarette.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.669, 7.645]} rotation={[-2.001, 0, 0]} scale={0}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cigarette.glb')
